
version: '3.4'

services:
  client:
    image: client:latest
    build:
      context: .
      dockerfile: src/DiscordRPG.Client/Dockerfile

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: